# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Listing Running

# Controls when the action will run. 
on:
  schedule:
    - cron: "* * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: node app.js
      env:
        RPC_PROVIDER: ${{ secrets.RPC_PROVIDER }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        ALEPH_ENDPOINT: ${{ secrets.ALEPH_ENDPOINT }}
        ALEPH_KEY: ${{ secrets.ALEPH_KEY }}
